### PR TITLE
'Port forward' option

### PR DESCRIPTION
**Pull request by sfate**
SSIA.

### CODE REVIEW

**Comment by paulirish** [comment]
@Sfate can you summarize this PR? There are a few things in here. It's also unclear how this port forward option operates with the port forwarding that's in DevTools experiments/settings.

**Comment by sfate** [comment]
So in general changes are:
- Added inputs for submitting port by user + validations for it
- Moved all style onto css-file
- Specified port writes at data attribute for hidden element in background.html
- On 'port submit' value sends to plugin for evaluating adb command: `forward tcp:$PORT localabstract:chrome_devtools_remote`
- After 'port forward' by click on "View devices" user locates to `localhost:$PORT`
- Rewrote method to getting path for `adb_command.sh` file

About 'port forward' in DevTools Experiments. It doesn't affect on it at all. It's just wrapper for adb tool.
Maybe when some API for it would be available then extension can be rewritten to work with DevTools Experiments.

**Comment by paulirish** [comment]
closed in favor of the first class port forwarding now in devtools

**Comment by paulirish** [comment]
@sfate thanks again for the PR and detailed summary. We liked it so much we baked it right in. :)

**Comment by sfate** [comment]
@paulirish cool. Thx for the notice. ;)

**Pull request closed without merging**
